export interface Country {
  code: string;
  name: string;
  flag: string;
}

export const countries: Country[] = [
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪' },
  { code: 'AR', name: 'Argentine', flag: '🇦🇷' },
  { code: 'PY', name: 'Paraguay', flag: '🇵🇾' },
  { code: 'BR', name: 'Brésil', flag: '🇧🇷' },
  { code: 'CO', name: 'Colombie', flag: '🇨🇴' },
  { code: 'PE', name: 'Pérou', flag: '🇵🇪' },
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾' },
  { code: 'CL', name: 'Chili', flag: '🇨🇱' },
  { code: 'EC', name: 'Équateur', flag: '🇪🇨' },
  { code: 'BO', name: 'Bolivie', flag: '🇧🇴' },
  { code: 'FR', name: 'France', flag: '🇫🇷' },
  { code: 'ES', name: 'Espagne', flag: '🇪🇸' },
  { code: 'IT', name: 'Italie', flag: '🇮🇹' },
  { code: 'DE', name: 'Allemagne', flag: '🇩🇪' },
  { code: 'GB', name: 'Angleterre', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹' },
  { code: 'NL', name: 'Pays-Bas', flag: '🇳🇱' },
  { code: 'BE', name: 'Belgique', flag: '🇧🇪' },
  { code: 'CI', name: 'Côte d\'Ivoire', flag: '🇨🇮' },
  { code: 'SN', name: 'Sénégal', flag: '🇸🇳' },
  { code: 'MA', name: 'Maroc', flag: '🇲🇦' },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬' },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭' },
  { code: 'CM', name: 'Cameroun', flag: '🇨🇲' },
  { code: 'EG', name: 'Égypte', flag: '🇪🇬' },
  { code: 'ZA', name: 'Afrique du Sud', flag: '🇿🇦' },
  { code: 'US', name: 'États-Unis', flag: '🇺🇸' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦' },
  { code: 'MX', name: 'Mexique', flag: '🇲🇽' },
  { code: 'JP', name: 'Japon', flag: '🇯🇵' },
  { code: 'CN', name: 'Chine', flag: '🇨🇳' },
  { code: 'IN', name: 'Inde', flag: '🇮🇳' },
  { code: 'KR', name: 'Corée du Sud', flag: '🇰🇷' },
  { code: 'TH', name: 'Thaïlande', flag: '🇹🇭' },
  { code: 'VN', name: 'Vietnam', flag: '🇻🇳' },
  { code: 'MY', name: 'Malaisie', flag: '🇲🇾' },
  { code: 'SG', name: 'Singapour', flag: '🇸🇬' },
  { code: 'AU', name: 'Australie', flag: '🇦🇺' },
  { code: 'NZ', name: 'Nouvelle-Zélande', flag: '🇳🇿' },
  { code: 'RU', name: 'Russie', flag: '🇷🇺' },
  { code: 'TR', name: 'Turquie', flag: '🇹🇷' },
  { code: 'SA', name: 'Arabie Saoudite', flag: '🇸🇦' },
  { code: 'AE', name: 'Émirats Arabes Unis', flag: '🇦🇪' },
  { code: 'IL', name: 'Israël', flag: '🇮🇱' },
  { code: 'NO', name: 'Norvège', flag: '🇳🇴' },
  { code: 'SE', name: 'Suède', flag: '🇸🇪' },
  { code: 'DK', name: 'Danemark', flag: '🇩🇰' },
  { code: 'FI', name: 'Finlande', flag: '🇫🇮' },
  { code: 'CH', name: 'Suisse', flag: '🇨🇭' },
  { code: 'AT', name: 'Autriche', flag: '🇦🇹' },
  { code: 'PL', name: 'Pologne', flag: '🇵🇱' },
  { code: 'CZ', name: 'République Tchèque', flag: '🇨🇿' },
  { code: 'HU', name: 'Hongrie', flag: '🇭🇺' },
  { code: 'RO', name: 'Roumanie', flag: '🇷🇴' },
  { code: 'BG', name: 'Bulgarie', flag: '🇧🇬' },
  { code: 'GR', name: 'Grèce', flag: '🇬🇷' },
  { code: 'HR', name: 'Croatie', flag: '🇭🇷' },
  { code: 'RS', name: 'Serbie', flag: '🇷🇸' },
  { code: 'UA', name: 'Ukraine', flag: '🇺🇦' },
  { code: 'BY', name: 'Biélorussie', flag: '🇧🇾' },
  { code: 'LT', name: 'Lituanie', flag: '🇱🇹' },
  { code: 'LV', name: 'Lettonie', flag: '🇱🇻' },
  { code: 'EE', name: 'Estonie', flag: '🇪🇪' },
  { code: 'IE', name: 'Irlande', flag: '🇮🇪' },
  { code: 'IS', name: 'Islande', flag: '🇮🇸' },
  { code: 'MT', name: 'Malte', flag: '🇲🇹' },
  { code: 'CY', name: 'Chypre', flag: '🇨🇾' },
  { code: 'LU', name: 'Luxembourg', flag: '🇱🇺' },
  { code: 'MC', name: 'Monaco', flag: '🇲🇨' },
  { code: 'AD', name: 'Andorre', flag: '🇦🇩' },
  { code: 'SM', name: 'Saint-Marin', flag: '🇸🇲' },
  { code: 'VA', name: 'Vatican', flag: '🇻🇦' },
  { code: 'LI', name: 'Liechtenstein', flag: '🇱🇮' },
  { code: 'BJ', name: 'Bénin', flag: '🇧🇯' },
  { code: 'NE', name: 'Niger', flag: '🇳🇪' },
  { code: 'TG', name: 'Togo', flag: '🇹🇬' },
  { code: 'ML', name: 'Mali', flag: '🇲🇱' },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫' },
  { code: 'GN', name: 'Guinée', flag: '🇬🇳' },
  { code: 'GW', name: 'Guinée-Bissau', flag: '🇬🇼' },
  { code: 'SL', name: 'Sierra Leone', flag: '🇸🇱' },
  { code: 'LR', name: 'Liberia', flag: '🇱🇷' },
  { code: 'MR', name: 'Mauritanie', flag: '🇲🇷' },
  { code: 'GM', name: 'Gambie', flag: '🇬🇲' },
  { code: 'CV', name: 'Cap-Vert', flag: '🇨🇻' },
  { code: 'ST', name: 'São Tomé-et-Príncipe', flag: '🇸🇹' },
  { code: 'GQ', name: 'Guinée équatoriale', flag: '🇬🇶' },
  { code: 'GA', name: 'Gabon', flag: '🇬🇦' },
  { code: 'CG', name: 'Congo', flag: '🇨🇬' },
  { code: 'CD', name: 'République démocratique du Congo', flag: '🇨🇩' },
  { code: 'CF', name: 'République centrafricaine', flag: '🇨🇫' },
  { code: 'TD', name: 'Tchad', flag: '🇹🇩' },
  { code: 'DJ', name: 'Djibouti', flag: '🇩🇯' },
  { code: 'ER', name: 'Érythrée', flag: '🇪🇷' },
  { code: 'ET', name: 'Éthiopie', flag: '🇪🇹' },
  { code: 'SO', name: 'Somalie', flag: '🇸🇴' },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪' },
  { code: 'UG', name: 'Ouganda', flag: '🇺🇬' },
  { code: 'TZ', name: 'Tanzanie', flag: '🇹🇿' },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼' },
  { code: 'BI', name: 'Burundi', flag: '🇧🇮' },
  { code: 'MW', name: 'Malawi', flag: '🇲🇼' },
  { code: 'ZM', name: 'Zambie', flag: '🇿🇲' },
  { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼' },
  { code: 'BW', name: 'Botswana', flag: '🇧🇼' },
  { code: 'NA', name: 'Namibie', flag: '🇳🇦' },
  { code: 'SZ', name: 'Eswatini', flag: '🇸🇿' },
  { code: 'LS', name: 'Lesotho', flag: '🇱🇸' },
  { code: 'MZ', name: 'Mozambique', flag: '🇲🇿' },
  { code: 'MG', name: 'Madagascar', flag: '🇲🇬' },
  { code: 'MU', name: 'Maurice', flag: '🇲🇺' },
  { code: 'SC', name: 'Seychelles', flag: '🇸🇨' },
  { code: 'KM', name: 'Comores', flag: '🇰🇲' },
  { code: 'YT', name: 'Mayotte', flag: '🇾🇹' },
  { code: 'RE', name: 'La Réunion', flag: '🇷🇪' },
  { code: 'DZ', name: 'Algérie', flag: '🇩🇿' },
  { code: 'TN', name: 'Tunisie', flag: '🇹🇳' },
  { code: 'LY', name: 'Libye', flag: '🇱🇾' },
  { code: 'SD', name: 'Soudan', flag: '🇸🇩' },
  { code: 'SS', name: 'Soudan du Sud', flag: '🇸🇸' },
  { code: 'AO', name: 'Angola', flag: '🇦🇴' },
  { code: 'BJ', name: 'Bénin', flag: '🇧🇯' },
  { code: 'NE', name: 'Niger', flag: '🇳🇪' },
  { code: 'CM', name: 'Cameroun', flag: '🇨🇲' },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬' },
  { code: 'TG', name: 'Togo', flag: '🇹🇬' },
  { code: 'ML', name: 'Mali', flag: '🇲🇱' },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫' },
  { code: 'GN', name: 'Guinée', flag: '🇬🇳' },
  { code: 'GW', name: 'Guinée-Bissau', flag: '🇬🇼' },
  { code: 'SL', name: 'Sierra Leone', flag: '🇸🇱' },
  { code: 'LR', name: 'Liberia', flag: '🇱🇷' },
  { code: 'MR', name: 'Mauritanie', flag: '🇲🇷' },
  { code: 'GM', name: 'Gambie', flag: '🇬🇲' },
  { code: 'CV', name: 'Cap-Vert', flag: '🇨🇻' },
  { code: 'ST', name: 'São Tomé-et-Príncipe', flag: '🇸🇹' },
  { code: 'GQ', name: 'Guinée équatoriale', flag: '🇬🇶' },
  { code: 'GA', name: 'Gabon', flag: '🇬🇦' },
  { code: 'CG', name: 'Congo', flag: '🇨🇬' },
  { code: 'CD', name: 'République démocratique du Congo', flag: '🇨🇩' },
  { code: 'CF', name: 'République centrafricaine', flag: '🇨🇫' },
  { code: 'TD', name: 'Tchad', flag: '🇹🇩' },
  { code: 'DJ', name: 'Djibouti', flag: '🇩🇯' },
  { code: 'ER', name: 'Érythrée', flag: '🇪🇷' },
  { code: 'ET', name: 'Éthiopie', flag: '🇪🇹' },
  { code: 'SO', name: 'Somalie', flag: '🇸🇴' },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪' },
  { code: 'UG', name: 'Ouganda', flag: '🇺🇬' },
  { code: 'TZ', name: 'Tanzanie', flag: '🇹🇿' },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼' },
  { code: 'BI', name: 'Burundi', flag: '🇧🇮' },
  { code: 'MW', name: 'Malawi', flag: '🇲🇼' },
  { code: 'ZM', name: 'Zambie', flag: '🇿🇲' },
  { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼' },
  { code: 'BW', name: 'Botswana', flag: '🇧🇼' },
  { code: 'NA', name: 'Namibie', flag: '🇳🇦' },
  { code: 'SZ', name: 'Eswatini', flag: '🇸🇿' },
  { code: 'LS', name: 'Lesotho', flag: '🇱🇸' },
  { code: 'MZ', name: 'Mozambique', flag: '🇲🇿' },
  { code: 'MG', name: 'Madagascar', flag: '🇲🇬' },
  { code: 'MU', name: 'Maurice', flag: '🇲🇺' },
  { code: 'SC', name: 'Seychelles', flag: '🇸🇨' },
  { code: 'KM', name: 'Comores', flag: '🇰🇲' },
  { code: 'YT', name: 'Mayotte', flag: '🇾🇹' },
  { code: 'RE', name: 'La Réunion', flag: '🇷🇪' },
  { code: 'DZ', name: 'Algérie', flag: '🇩🇿' },
  { code: 'TN', name: 'Tunisie', flag: '🇹🇳' },
  { code: 'LY', name: 'Libye', flag: '🇱🇾' },
  { code: 'SD', name: 'Soudan', flag: '🇸🇩' },
  { code: 'SS', name: 'Soudan du Sud', flag: '🇸🇸' },
  { code: 'AO', name: 'Angola', flag: '🇦🇴' },
  { code: 'BJ', name: 'Bénin', flag: '🇧🇯' },
  { code: 'NE', name: 'Niger', flag: '🇳🇪' },
  { code: 'CM', name: 'Cameroun', flag: '🇨🇲' },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬' },
  { code: 'TG', name: 'Togo', flag: '🇹🇬' },
  { code: 'ML', name: 'Mali', flag: '🇲🇱' },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫' },
  { code: 'GN', name: 'Guinée', flag: '🇬🇳' },
  { code: 'GW', name: 'Guinée-Bissau', flag: '🇬🇼' },
  { code: 'SL', name: 'Sierra Leone', flag: '🇸🇱' },
  { code: 'LR', name: 'Liberia', flag: '🇱🇷' },
  { code: 'MR', name: 'Mauritanie', flag: '🇲🇷' },
  { code: 'GM', name: 'Gambie', flag: '🇬🇲' },
  { code: 'CV', name: 'Cap-Vert', flag: '🇨🇻' },
  { code: 'ST', name: 'São Tomé-et-Príncipe', flag: '🇸🇹' },
  { code: 'GQ', name: 'Guinée équatoriale', flag: '🇬🇶' },
  { code: 'GA', name: 'Gabon', flag: '🇬🇦' },
  { code: 'CG', name: 'Congo', flag: '🇨🇬' },
  { code: 'CD', name: 'République démocratique du Congo', flag: '🇨🇩' },
  { code: 'CF', name: 'République centrafricaine', flag: '🇨🇫' },
  { code: 'TD', name: 'Tchad', flag: '🇹🇩' },
  { code: 'DJ', name: 'Djibouti', flag: '🇩🇯' },
  { code: 'ER', name: 'Érythrée', flag: '🇪🇷' },
  { code: 'ET', name: 'Éthiopie', flag: '🇪🇹' },
  { code: 'SO', name: 'Somalie', flag: '🇸🇴' },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪' },
  { code: 'UG', name: 'Ouganda', flag: '🇺🇬' },
  { code: 'TZ', name: 'Tanzanie', flag: '🇹🇿' },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼' },
  { code: 'BI', name: 'Burundi', flag: '🇧🇮' },
  { code: 'MW', name: 'Malawi', flag: '🇲🇼' },
  { code: 'ZM', name: 'Zambie', flag: '🇿🇲' },
  { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼' },
  { code: 'BW', name: 'Botswana', flag: '🇧🇼' },
  { code: 'NA', name: 'Namibie', flag: '🇳🇦' },
  { code: 'SZ', name: 'Eswatini', flag: '🇸🇿' },
  { code: 'LS', name: 'Lesotho', flag: '🇱🇸' },
  { code: 'MZ', name: 'Mozambique', flag: '🇲🇿' },
  { code: 'MG', name: 'Madagascar', flag: '🇲🇬' },
  { code: 'MU', name: 'Maurice', flag: '🇲🇺' },
  { code: 'SC', name: 'Seychelles', flag: '🇸🇨' },
  { code: 'KM', name: 'Comores', flag: '🇰🇲' },
  { code: 'YT', name: 'Mayotte', flag: '🇾🇹' },
  { code: 'RE', name: 'La Réunion', flag: '🇷🇪' },
  { code: 'DZ', name: 'Algérie', flag: '🇩🇿' },
  { code: 'TN', name: 'Tunisie', flag: '🇹🇳' },
  { code: 'LY', name: 'Libye', flag: '🇱🇾' },
  { code: 'SD', name: 'Soudan', flag: '🇸🇩' },
  { code: 'SS', name: 'Soudan du Sud', flag: '🇸🇸' },
  { code: 'AO', name: 'Angola', flag: '🇦🇴' },
  { code: 'ZA', name: 'Afrique du Sud', flag: '🇿🇦' }
];

export const getCountryByName = (name: string): Country | undefined => {
  return countries.find(country => 
    country.name.toLowerCase().includes(name.toLowerCase()) ||
    name.toLowerCase().includes(country.name.toLowerCase())
  );
};

export const getCountryFlag = (countryName: string): string => {
  const country = getCountryByName(countryName);
  return country?.flag || '🏳️';
};

export const getLeagueCountry = (leagueName: string): string => {
  const leagueCountryMap: { [key: string]: string } = {
    'Venezuela Super': 'Venezuela',
    'Liga Argentina B': 'Argentine',
    'Réserve de Barra': 'Paraguay',
    'Liga Brasileira': 'Brésil',
    'Liga Colombiana': 'Colombie',
    'Liga Peruana': 'Pérou',
    'Liga Uruguaya': 'Uruguay',
    'Liga Chilena': 'Chili',
    'Liga Ecuatoriana': 'Équateur',
    'Liga Boliviana': 'Bolivie',
    'Ligue 1': 'France',
    'La Liga': 'Espagne',
    'Serie A': 'Italie',
    'Bundesliga': 'Allemagne',
    'Premier League': 'Angleterre',
    'Primeira Liga': 'Portugal',
    'Eredivisie': 'Pays-Bas',
    'Pro League': 'Belgique',
    'Ligue Ivoirienne': 'Côte d\'Ivoire',
    'Ligue Sénégalaise': 'Sénégal',
    'Botola Pro': 'Maroc',
    'NPFL': 'Nigeria',
    'Ghana Premier League': 'Ghana',
    'Elite One': 'Cameroun',
    'Egyptian Premier League': 'Égypte',
    'PSL': 'Afrique du Sud',
  };

  return leagueCountryMap[leagueName] || 'France';
};